### ISSUE TITLE
Fisrt Blog

### ISSUE THREAD

**Issue by shiyang07ca** [shiyang07ca/shiyang07ca.github.io#1]
Test update 

## TODO: blog 优化
- [ ] 配置 MkDocs 作为笔记子目录
- [ ] 支持 issue DRAFT 标签，zola 编译时不渲染文章
- [ ] issue 标签自动嵌入 zola 模板中
- [ ] 优化文件自动备份策略
- [ ] 测试图片嵌入
- [ ] 测试公式
- [ ] 申请域名
- [ ] 配置 CDN 加速
- [ ] 测试 Vercel 部署
